### ISSUE TITLE
I'm confused. Where are the benchmark results?

### ISSUE THREAD

**Issue by samal-rasmussen** [ThePrimeagen/leftPadDeez#11]
I'm confused. Where are the benchmark results?

**Comment by PickleNik** [comment]
> I'm confused. Where are the benchmark results?

deez?
https://twitter.com/EmberHext/status/1653096327675346945
https://twitter.com/techsavvytravvy/status/1653672117081108483
https://twitter.com/ESArnau/status/1653151823274942472
https://twitter.com/EmberHext/status/1653778878572253186
