### ISSUE TITLE
Why the heck is the image in png and not webp/avif?

### ISSUE THREAD

**Issue by maddsua** [ThePrimeagen/leftPadDeez#7]
Do you hate the performance or something?

**Comment by PickleNik** [comment]
<img width="837" alt="Screenshot 2023-05-05 at 8 50 03 PM" src="https://user-images.githubusercontent.com/31113245/236589397-c5fd1c8e-57d8-4514-af38-ebc4854a1b14.png">
Github doesn't support it by drag'n'drop, could just add the file to the repo and link to it tho

**Comment by maddsua** [comment]
Nice
